{% set version = '0.6.3' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-googlevis
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/googleVis_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/googleVis/googleVis_{{ version }}.tar.gz
  sha256: 17d104c5d4e6ab7b984df229cd51be19681e4726077afec7c61a33f6e4c0b6ef

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-jsonlite
  run:
    - r-base
    - r-jsonlite

test:
  commands:
    - $R -e "library('googleVis')"           # [not win]
    - "\"%R%\" -e \"library('googleVis')\""  # [win]

about:
  home: https://github.com/mages/googleVis#googlevis
  license: GPL (>= 2)
  summary: R interface to Google's chart tools, allowing users to create interactive charts based
    on data frames. Charts are displayed locally via the R HTTP help server. A modern
    browser with an Internet connection is required and for some charts a Flash player.
    The data remains local and is not uploaded to Google.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: googleVis
# Type: Package
# Title: R Interface to Google Charts
# Version: 0.6.3
# Date: 2018-11-12
# Authors@R: c(person("Markus", "Gesmann", role = c("aut", "cre"), email = "markus.gesmann@googlemail.com"), person("Diego", "de Castillo", role = "aut", email = "decastillo@gmail.com"), person("Joe", "Cheng", role = "ctb", email = "joe@rstudio.com"))
# Description: R interface to Google's chart tools, allowing users to create interactive charts based on data frames. Charts are displayed locally via the R HTTP help server. A modern browser with an Internet connection is required and for some charts a Flash player. The data remains local and is not uploaded to Google.
# Depends: R (>= 3.0.2)
# Imports: methods, jsonlite, utils
# Suggests: shiny (>= 0.4.0), httpuv (>= 1.2.0), knitr (>= 1.5), wbstats, data.table
# License: GPL (>= 2)
# URL: https://github.com/mages/googleVis#googlevis
# BugReports: https://github.com/mages/googleVis/issues
# LazyLoad: yes
# LazyData: yes
# VignetteBuilder: knitr
# RoxygenNote: 6.1.0
# NeedsCompilation: no
# Packaged: 2018-11-12 14:44:07 UTC; mages
# Author: Markus Gesmann [aut, cre], Diego de Castillo [aut], Joe Cheng [ctb]
# Maintainer: Markus Gesmann <markus.gesmann@googlemail.com>
# Repository: CRAN
# Date/Publication: 2018-11-12 16:10:03 UTC
