travis:
  secure:
    BINSTAR_TOKEN: l+mNtm1sw1/NCNa8ZWI4YnOgCGzCITPShMiDgmNwrRW4NU+5fwABG+TpWOrV2YDGEmk7zJcnDn1S0scdQ61MdTurADESl/1rOEHZqRi4W14D9fDqPyH+UHuKoZ80oXWbvubNHlMdfQ0gttGXOU48oEsEVofbQGjP4ekjIkdPaEiWsrzNmUH6Z2xwhGK5cJxjSXb++J8pfuBp5toFV2Xm4wZflq1lkOteNX0Q8Z294EjUEsIvo9nHbH0NDp4hsvH1PegBTs9ccCXLiBcG7N3at3+W6cQAJs8WDKUQRnfeFsoKQNdDxKiVDn93TwjuxFGke+0brOgS7T4CC+1vWdgrKo56wgJOSvCmY48hhExHq7ChaDMYJeIHA9zuHg6rDhyoddf25JCRGSvCbOXMphHcGYAJ0eZlRNtgmDsivaNSbnCXa13JGU8fXrlShhxXZyCyHDpiZbySX2wELGvi/n5eEOmsyXjEgdNvo4zR77RzqmcGwtHKu0x0OkIqDagkI2kjKFlals2reySlYPZNdkGICp9lUc8RnABRsIqn5Iq/r8wVljNEwvTZhV04NFFcPicxyfcrVs65dQumYp0Ky6lBIxFEZuvF1dibBo6x7pf6nfgLGLM0BH6wIVnji+xruiy3GG2OZqEZDlOiHY09h1nEfRJLhNlxH3VgYAJDiVAS0G0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
