appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: HwG/DE6xQ4t2G1ehJZAnyGgPxQ9r6QkpTaoXlG4amWSkoXpDrh3A/EzDlJwt77euUVBVGQEotcbszpb+a28zGMZWmamq3LVHcu4KrMhlcR8q1mI7Nw8sSwr+HbvBQ1MX1p5dzMmrUVKaxV52oF2cAX/PHcG3f0aev/T7dpicGq9onaQADNlOAT3y/AAShngJJ1zi7Ca8LiSdX+sVVubaP+2TOcC1W5Cca3SjMbCnMcXXy17J8DxWdSe/SELIrwlW63fYs5gjgpTgq6B4VWd/uIZHnfvv+Tx3rxX+mxg8/8/+pdkKuAaG2vmttPdvikgxNv8Dwkc1l7SXT26YJndIvflyeMjQADHS+0Qg9Ro97vpT0x5VBM0ZT9xQUDR9JZ2AV2fj9r1V2ZE4bHUVwsT5TQZWoQ0I85puFJyRUydjdJsh5qhm/zpdaBECftgEx4BZ4wGodvCNsatWC9CqmGW5U5A40czE3BqlSYb+6XPktPaMY+6IBplVMXOU7vxNRqtDe2VeK4amxvHUOmoN8RxQQ+3vGNzYxxLS94UfHnt9NYHIoAizSNyeRrGFgySI3Q3FkNwjJpakZfY4LK1rPdNxcGp9ukHbguv1IYabQ0dQDsMDDJ8IiLr4ADD8mvI/6dKgljgi86dx3x7LLGBAbXrBBHq4YYS6Xd6avVmvMztSEIQ=}
bot:
  automerge: true
